version: "3.9"
services:
  Chi-chan:
    image: seker212/discord_bot
    environment:
      - TOKEN=0
    volumes: 
      - ./audio:/app/audio
      - ./settings:/app/settings
      - ./logs:/app/logs