version: "3.9"
services:
  DiscordBot:
    image: seker212/discord_bot:2.0
    build: 
      context: .
    environment:
      - TOKEN=ODIzNjEyMDM5NzI5NjQzNTMy.YFjWfA.95izYP_cY86t961XHsYJXUykzrY
      - SEQ_URL=http://seq:5341
    volumes: 
      - ./audio:/app/audio
      - ./data:/app/data
  seq:
    image: datalust/seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8080:80
    volumes:
      - ./seq:/data