response = ['No i co ty chcesz?',
'Nudzi ci się?',
'Zadania byś robił',
'Prace byś se znalazł',
'A gdyby tak w minecraft grać',
'Może pójdziesz spać?',
'Czy ty wiesz która to jest godzina?',
'Znowu?',
'No i co to ma znaczyć?',
'Pozaczepiaj kogo innego',
'Masz nice on cottage',
'Oj tak tak byczq +1',
'Mi też się nudzi może porobimy to razem?',
'To że co Ola studiuje?',
'Napewno nie oglądam anime',
'Kiedy minecraft?',
'Nudno jest tak pisać odpowiedzi',
'Kiedyś to było teraz to nie ma',
'A co gdyby tak...',
'No i fajnie',
'Takie nastawienie do życie to ja lubie',
'Nie zesraj się', 
'Na koniec świata i jeszcze dalej', 
'Mam to w dupie', 
'Nie odzywaj się do mnie', 
'Wkurwiasz mnie', 
'Przerzuć się na Linuxa',  
'W restauracji:\n - Jak panu smakował chłodnik?\n - Dupy nie urywa.\n - Cierpliwości.', 
'Przychodzi baba a do lekarza a lekarz', 'Ja nie wiem, u mnie działa', 
'Ale że co ty tu jeszcze robisz!?', 
'Twoja stara to kopara a Twój stary ją odpala.', 
'Czekaj no, łapię pokémona', 
'Bo wiecie', 
'Jak nie masz nic pożytecznego do roboty to znajdź jakiegoś śmiesznego mema', 
'Brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
'Wypierdalaj, gram w WEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'Chcesz coś? Dopisz sobie',
'To kiedy Hori?',
'Ja nic']


facts = ['Korea Północna i Kuba to jedyne miejsca, w których nie można kupić Coca-Coli.',
'17 Polaków otrzymało Nagrodę Nobla, czyli więcej niż w Japonii, Chinach, Indiach czy Australii.',
'Francja jest najczęściej odwiedzanym krajem na świecie.',
'Zaskakujące jest, że Australia jest najbardziej otyłym krajem na świecie od 2012 r., a odsetek otyłości wynosi 26 procent.',
'W kasynach hazardowych w Las Vegas nie ma zegarów.',
'Honolulu to jedyne miejsce w Stanach Zjednoczonych, które posiada pałac królewski.',
'Hiszpania jest uważana za najbardziej górzysty kraj w Europie, a ma ponad 8000 km plaż.',
'Stany Zjednoczone nie posiadają języka urzędowego.',
'Jedna trzecia wszystkich portów lotniczych na świecie znajduje się w Stanach Zjednoczonych.',
'Mexico City tonie w tempie 10 cm rocznie, 10 razy szybciej niż Wenecja.',
'Arabia Saudyjska jest jedynym krajem na świecie, w którym nie ma rzek.',
'Mówi się, że Wielki Mur można zobaczyć z kosmosu, ale w rzeczywistości tak nie jest.',
'Karaluch może żyć kilka tygodni bez głowy. W końcu umrze z głodu.',
'Środkowy palec Galileusza jest przechowywany w Muzeum Nauki we Florencji.',
'IPhone, książki o Harrym Potterze i Kostka Rubika to 3 najlepiej sprzedające się produkty w historii ludzkości.',
'Obraz Mona Lisy przez kilka lat wisiał w sypialni Napoleona Bonaparte.',
'Fenomen bombajski to zjawisko, w którym brakuje niektórych elementów krwi. Powoduje to, że osoba ma mieszaną grupę krwi. Tylko 0, 0004% światowej populacji ma taką krew. Istnieje nawet specjalne przechowywanie tej krwi, aby ludzie, którzy ją posiadają, mogli w razie potrzeby dokonać transfuzji krwi. Co ciekawe, ta wyjątkowa grupa krwi może zostać przetoczona przez każdą osobę z regularną grupą krwi.',
'Oprócz zmysłów, które wszyscy znamy, takich jak węch i dotyk, człowiek ma także inne zmysły: propriocepcja (świadomość pozycji części ciała).',
'Kiedy założono Los Angeles, miasto nosiło pierwszą nazwę „El Pueblo de Nuestra Senora Reina de Los Angeles Sobre el Rio Porciuncula”. To, przetłumaczone z hiszpańskiego, ujawnia piękne znaczenie: „Miasto naszej Pani Królowej Aniołów na rzece Porcjunkuli”.',
'W Niemczech sprzedaje się więcej gier planszowych niż gdziekolwiek indziej na Ziemi.',
'Mayday to słowo, które jest używane zamiast SOS na czacie radiowym.',
'Postacie Pokemon Hitmonlee i Hitmonchan zostały nazwane na cześć Bruce’a Lee i Jackie Chana.',
'Hiszpańskie słowo „esposas” oznacza zarówno „kajdanki”, jak i „żony”.',
'Niebieski ptak z logo Twittera ma nazwę: Larry. Twórcy sieci społecznościowej nazwali ptaka imieniem koszykarza Larry’ego Birda.',
'W wysokogórskich lasach Nepalu występują gigantyczne pszczoły. Ich długość może wynosić do 2,50 cm. Te pszczoły wytwarzają specjalny miód, który może powodować halucynacje. Gurungowie mieszkający w tej części Himalajów zbierają ten halucynogenny miód.',
'Kiedy przybierasz na wadze lub tracisz na wadze, twoje komórki tłuszczowe nie znikają – po prostu zmieniają swój rozmiar.',
'Niektóre japońskie światła drogowe mają niebieskie zamiast zielonych, ponieważ historycznie oba kolory były nazywane tym samym słowem.',
'99% drobnoustrojów żyjących w ludziach jest nieznanych nauce.',
'Ostatnie słowa, które wypowiedział Albert Einstein, są nieznane, ponieważ wypowiedział je po niemiecku do pielęgniarki, która nie znała tego języka.',
'Cięcie papierem jest bardziej bolesne niż zwykłe cięcie, ponieważ taka rana prawie nigdy nie krwawi, więc zakończenia nerwowe pozostają otwarte na powietrze, co je drażni.',
'Wszystkie koty były uważane za święte w starożytnym Egipcie. Jeśli zabiłeś kota, mogłeś być skazany na śmierć.',
'Kiedy bierzesz gorącą kąpiel, spalasz tyle kalorii, ile byś spalił na 30-minutowym spacerze.',
'W 2011 r. Korea Północna przekazała Japonii 500 tysięcy dolarów amerykańskich, kiedy miało miejsce trzęsienie ziemi.',
'Kiedy ekshumowano ciało Salvadora Dali w czerwcu 2017 r., wąsy miały dokładnie taką długość jak w dniu jego śmierci.',
'Najpopularniejszym prezentem w Dzień Ojca jest krawat.',
'W 1939 roku amerykański kompozytor i pianista Earl Wild dał pierwszy koncert na świecie, który był transmitowany w telewizji na żywo. 58 lat później jego występ był pierwszym koncertem online w Internecie.',
'Jeśli zrobisz kostki lodu za pomocą wody z kranu, będą one białe. Jeśli użyjesz przegotowanej wody, będą one przezroczyste.',
'Nazwiska Van, Lee i Zhang są najbardziej popularne na świecie. Ma je ​​21% całej populacji Chin.',
'Zwierzęta unikają linii energetycznych, ponieważ boją się błysków ultrafioletowych, których ludzkie oko nie widzi. Nawiasem mówiąc, ze wszystkich ssaków na świecie tylko ludzie i małpy nie widzą promieni ultrafioletowych.',
'Tokelau, grupa odległych wysp na Oceanie Spokojnym, generuje 100 procent energii elektrycznej z energii słonecznej.',
'Charles Darwin był pierwszą osobą, która wpadła na pomysł, aby przymocować koła do krzesła biurowego, aby szybciej się poruszać.',
'W 2011 r. Kobieta o imieniu Aimee Davison zakupiła „niewidoczne” dzieło za 10 000 USD.',
'Najostrzejsza papryczka chili na świecie jest tak ostra, że ​​może cię zabić.',
'Najgęściej zaludniona wyspa na świecie ma rozmiar dwóch boisk do piłki nożnej.',
'Wyspy Kanaryjskie noszą nazwy od psów, a nie ptaków.',
'Indonezja jest domem dla jednych z najniższych ludzi na świecie.Zgodnie z danymi zebranymi z różnych globalnych źródeł przez Telegraph w 2017 roku. Średnia wysokość mężczyzn wynosi 158 cm.',
'Najwyżsi ludzie wśród nas mieszkają w Holandii, gdzie średnia wysokość dorosłego mężczyzny wynosi 184 cm.',
'Porozumienie paryskie w sprawie zmian klimatu zostało podpisane przez największą liczbę krajów w ciągu jednego dnia.',
'Najcichszy pokój na świecie znajduje się w siedzibie Microsoftu w stanie Waszyngton.',
'Są tylko trzy kraje na świecie, które nie korzystają z systemu metrycznego. Dla uproszczenia większość z ponad 200 krajów na świecie używa systemu metrycznego przy opisywaniu rzeczy takich jak długość czy masa. Jednak wyróżniają się trzy kraje: Liberia, Birma i Stany Zjednoczone.',
'Najdłuższa nazwa miejsca na świecie ma 85 liter.',
'Radom ma o wiele większą powierzchnię niż Paryż. Liczba ludności Paryża jest prawie dziesięciokrotnie większa w Radomiu.',
'Japonia jest najbardziej narażonym na trzęsienia ziemi krajem na świecie.',
'Na Ziemi jest około 4 „biliardy biliardów” bakterii.',
'Ludzie, którzy obecnie żyją, stanowią około 7 procent całkowitej liczby osób, które kiedykolwiek żyły.',
'Muhammad to najpopularniejsze imię na świecie.',
'Tylko 2 kraje mają w swojej fladze kolor fioletowy. Flaga Nikaragui ma tęczę pośrodku z pasmem fioletu, a flaga Dominiki przedstawia zdjęcie papugi, ptaka z fioletowymi piórami.',
'Afryka i Azja są domem dla prawie 90% ludności wiejskiej na świecie.',
'Najdroższa moneta na świecie została sprzedana za ponad 7 milionów dolarów.',
'Największa na świecie sztuczna rafa ostrygowa została stworzona w Maryland.',
'Rekordowe 92 kraje rywalizowały w Zimowych Igrzyskach Olimpijskich w 2018 roku.',
'Czarne niedźwiedzie czasami hibernują się na szczytach drzew.',
'Ponad 52% Sudanu światowej populacji ma mniej niż 30 lat.',
'Na świecie istnieje ponad 24 stref czasowych.',
'Prawie połowa światowej populacji oglądała zarówno mecze Mistrzostw Świata FIFA 2010, jak i 2014.',
'Szacuje się, że Szwecja ma więcej wysp niż jakikolwiek inny kraj.',
'Istnieją 43 kraje, które wciąż posiadają rodzinę królewską.',
'Wszystkie gigantyczne pandy w ogrodach zoologicznych na całym świecie są wypożyczone z Chin.',
'Kanada ma 9% lasów na świecie.',
'Quelea jest najczęstszym ptakiem na Ziemi.',
'W 1889 roku królowa Włoch, Margherita Savoy, zamówiła pierwszą pizzę z dowozem.',
'Więcej osób mówi po chińsku (mandaryńsku) niż w jakimkolwiek innym języku.',
'Około jeden na 200 mężczyzn jest bezpośrednim potomkiem Czyngis-chana.',
'Kopenhaga jest najbardziej przyjaznym rowerom miastem na świecie.',
'Istnieje 41 krajów, które uznają język migowy za język urzędowy.',
'Globalny wskaźnik alfabetyzacji dorosłych wynosi około 86%. Z każdym pokoleniem, które mija, coraz więcej osób uczy się czytać, zgodnie z Organizacją Narodów Zjednoczonych ds. Edukacji, Nauki i Kultury (UNESCO). Dane pokazują „znaczną poprawę wśród młodzieży pod względem umiejętności czytania i pisania oraz stałe zmniejszanie różnic między płciami. Pięćdziesiąt lat temu prawie jedna czwarta młodzieży nie posiadała podstawowych umiejętności czytania i pisania w porównaniu do mniej niż 10% w 2016 r. ”',
'Facebook ma więcej użytkowników niż USA, Chiny i Brazylia łącznie.',
'Tylko Gambia i Bahamy formalnie zawierają „The” w nazwach swoich narodów.',
'Wszystkie mrówki na Ziemi ważą mniej więcej tyle samo, co wszyscy ludzie. Całkowita populacja ludzi żyjących na Ziemi nie przekroczyła nawet 8 miliardów. Jednocześnie w danym momencie krąży 10 biliardów (10 000 000 000 000 000) pojedynczych mrówek.',
'Oceany zawierają prawie 200 tysięcy różnych rodzajów wirusów.',
'Nowozelandczycy mają więcej zwierząt domowych niż ludzie w jakimkolwiek innym kraju. 68% gospodarstw domowych w kraju ma zwierzaka. Amerykanie również uwielbiają futrzanych przyjaciół, dlatego ponad połowa wszystkich amerykańskich domów ma psa lub kota.',
'Tokio jest największym miastem na świecie z 37 milionami mieszkańców. Tokio to prężnie rozwijające się miasto, nie tylko według japońskich standardów, ale także w porównaniu z miastami na całym świecie. Kolejne największe miasto to Delhi w Indiach (29 milionów mieszkańców) i Szanghaj w Chinach (26 milionów).',
'Interpol rozpoczął działalność w 1914 r., kiedy prawnicy z 24 krajów spotkali się, aby omówić metody szukania zbiegów.',
'Podczas gdy czworo dzieci rodzi się na Ziemi co sekundę, szacuje się, że około dwóch osób umiera w tym samym czasie. Oznacza to, że co minutę umiera 105 osób, 6316 osób co godzinę, 151 600 osób każdego dnia i 55,3 miliona osób rocznie.',
'Najstarszy hotel na świecie działa od 705 roku n.e. Nishiyama Onsen Keiunkan w Yamanashi w Japonii jest rekordzistą Guinnessa jako najstarszy hotel na świecie. Hotel z gorącymi źródłami znajduje się u podnóża oszałamiających gór Akaishi i działa od czasu założenia go przez Fujiwara Mahito w 705 r. Od tego czasu jest w rękach około 52 pokoleń jednej rodziny od ponad 1300 lat.',
'Ziewanie chłodzi mózg. Badania przeprowadzone na uniwersytecie w Wiedniu sugerują, że ziewanie może odgrywać istotną rolę w chłodzeniu naszego mózgu. Jednak ziewanie w celu ochłodzenia mózgu „nie działa”, gdy temperatura zewnętrzna jest tak wysoka jak ciało, wyjaśnił Jorg Massen, główny autor badania.',
'Przepłynięcie pełnej długości rzeki Mississippi zajmuje 68 dni. 4 lipca 2002 r. Pływak maratonowy Martin Steel rozpoczął podróż w północnej Minnesocie, płynąc rzeką Mississippi o długości 2348 mil, starając się być pierwszą osobą, która płynie na całej jej długości. 9 września osiągnął swój cel, a po niesamowitej 68-dniowej podróży znalazł się w Zatoce Meksykańskiej w Luizjanie. Płynął około 34,5 mil dziennie.',
'Jabłko może istnieć do 10 miesięcy. Według Departamentu Rolnictwa USA, jeśli zerwiesz jabłko z drzewa, minie kilka tygodni, zanim zacznie mięknąć i gnić. Ale jeśli przechowujesz całe zbiory w „kontrolowanych warunkach atmosferycznych”, będzie to istniało do 10 miesięcy.',
'Słowo „tragedia” pochodzi od starożytnego greckiego słowa oznaczającego „pieśń kozła”. Chociaż „tragedia” to słowo, którego używamy do określenia strasznego wydarzenia lub smutnego wyniku, wywodzi się ono z angielskiego słowa „tragedia”, które można prześledzić od „tragēdia” średniowiecznej łaciny i łacińskiej „tragoedia”. i które finalnie pochodzi od starożytnego greckiego słowa „tragōidía”, co oznacza „pieśń kozła”.',
'Termin „astronauta” pochodzi od greckich słów oznaczających „Gwiazda” i „marynarz”.',
'Za niegrzeczne uważa się pisanie czerwonym tuszem w języku portugalskim.',
'W każdej chwili na Ziemi ma miejsce około 2000 burz.',
'Michał Anioł nie cierpiał malować Kaplicy Sykstyńskiej i napisał o tym wiersz.',
'Ponad milion planet Ziemi zmieściłby się w jednym Słońcu.',
'Kiedyś litera Z została usunięta z alfabetu na aż 200 lat.',
'Lody o smaku węgorza można kupić w Japonii.',
'Dreszcze, które odczuwasz podczas słuchania muzyki, spowodowane są przez dopaminę uwalniającą do mózgu.',
'Największa na świecie dynia ważyła więcej niż samochód.',
'Przeciętny, dorosły Polak wypija 94 litry piwa rocznie. Wychodzi na to, że statystyczny Polak wypija pół litra piwa co drugi dzień.']