response = ['No i co ty chcesz?',
'Nudzi ci się?',
'Zadania byś robił',
'Prace byś se znalazł',
'A gdyby tak w minecraft grać',
'Może pójdziesz spać?',
'Czy ty wiesz która to jest godzina?',
'Znowu?',
'No i co to ma znaczyć?',
'Pozaczepiaj kogo innego',
'Masz nice on cottage',
'Oj tak tak byczq +1',
'Mi też się nudzi może porobimy to razem?',
'To że co Ola studiuje?',
'Napewno nie oglądam anime',
'Kiedy minecraft?',
'Nudno jest tak pisać odpowiedzi',
'Kiedyś to było teraz to nie ma',
'A co gdyby tak...',
'No i fajnie',
'Takie nastawienie do życie to ja lubie',
'Nie zesraj się', 
'Na koniec świata i jeszcze dalej', 
'Mam to w dupie', 
'Nie odzywaj się do mnie', 
'Wkurwiasz mnie', 
'Przerzuć się na Linuxa',  
'W restauracji:\n - Jak panu smakował chłodnik?\n - Dupy nie urywa.\n - Cierpliwości.', 
'Przychodzi baba a do lekarza a lekarz', 'Ja nie wiem, u mnie działa', 
'Ale że co ty tu jeszcze robisz!?', 
'Twoja stara to kopara a Twój stary ją odpala.', 
'Czekaj no, łapię pokémona', 
'Bo wiecie', 
'Jak nie masz nic pożytecznego do roboty to znajdź jakiegoś śmiesznego mema', 
'Brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
'Wypierdalaj, gram w WEEEEEEEEEEEEEEEEEEEEEEEEEEE']