name: Chi-chan bot Container Builder 2.0

on: 
  push:
    branches: 
      - master-2.0
      # If 2.0 version lands in master branch this should be replaced.
      # - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Login do Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discord_bot:2.0
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
