name: Build and deploy docs

on: 
  push:
    branches: 
    - master-2.0
    # If 2.0 version lands in master branch this should be replaced.
    # - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
  
    - run: dotnet tool update -g docfx
    - run: docfx Docs/docfx.json
  
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Docs/_site
  